- datm.streams.xml
- drof.streams.xml
> Revert "Update ryf inputs"

- check_inputs.py
- config.yaml
- input.nml
- manifests/exe.yaml
- nuopc.runseq
Supports JRA55-do https://github.com/COSIMA/access-om3/pull/45
and uses latest spack dependencies https://github.com/COSIMA/access-om3/pull/48
Requires
```
module use /g/data/ik11/spack/0.20.1/share/modules/linux-rocky8-cascadelake
```
see [wiki](https://github.com/COSIMA/access-om3/wiki/Quick-start#running)
> use ACCESS-OM3 exe

- README.md
> Update README to include more information about the 1deg_jra55do_ryf configuration

- config.yaml
- manifests/input.yaml
> Restructure input directory

- datm.streams.xml
- drof.streams.xml
- generate_xml_datm.py
- generate_xml_drof.py
See #20 for context
Closes #20
> Set year_align=year_first in data streams for IAF configs

- ice_in
* Update CICE config to match OM2 CICE Config
* Turn on leap years for consistency across components (https://github.com/COSIMA/MOM6-CICE6/pull/23#issuecomment-1863835652)
> 1deg jra55do iaf iss23

- datm.streams.xml
- drof.streams.xml
- nuopc.runconfig
> Change start year to 1900

- config.yaml
- manifests/exe.yaml
see https://github.com/COSIMA/access-om3/issues/93
> update iaf exe to match spack module

- config.yaml
- manifests/exe.yaml
see https://github.com/COSIMA/access-om3/issues/93
> update ryf exe to match spack module

- doc/MOM_input
- doc/README_doc.md
- doc/config.yaml
- doc/nuopc.runconfig
- doc/nuopc.runseq
- doc/update_doc.sh
Adds `doc` dir for wiki searches - see https://github.com/COSIMA/access-om3/issues/75
Includes an `update_doc.sh` to keep it up to date, and also update the changelog.
> doc dir for wiki searches

- archive_cice_restarts.sh
- diag_table
- manifests/input.yaml
- nuopc.runconfig
- setup_cice_restarts.sh
Cherry-picked commits from #41. See https://github.com/COSIMA/access-om3/issues/106
> 1deg_jra55do_iaf: change case name to "access-om3"

- config.yaml
See https://github.com/COSIMA/access-om3/issues/114
> `1deg_jra55do_ryf`: Comment out project and shortpath from config.yaml

- config.yaml
See https://github.com/COSIMA/access-om3/issues/114
> `1deg_jra55do_iaf`: Comment out project and shortpath from config.yaml

- config.yaml
See https://github.com/COSIMA/access-om3/issues/114
> `025deg_jra55do_ryf`: Comment out project and shortpath from config.yaml

- config.yaml
- fd.yaml
- manifests/exe.yaml
Changes needed to use latest OM3 executable.
Contributes to https://github.com/COSIMA/access-om3/issues/118
> 025deg jra55do_ryf:update OM3 executable to latest version

- MOM_input
See https://github.com/COSIMA/access-om3/issues/164
> Set `Z_INIT_REMAP_GENERAL = True` : `1deg_jra55do_ryf`

- MOM_input
See https://github.com/COSIMA/access-om3/issues/164
> Set `Z_INIT_REMAP_GENERAL = True` : `025deg_jra55do_ryf`

- MOM_input
See https://github.com/COSIMA/access-om3/issues/164
> Set `Z_INIT_REMAP_GENERAL = True` : `1deg_jra55do_iaf`

- docs/MOM_parameter_doc.all
- docs/MOM_parameter_doc.debugging
- docs/MOM_parameter_doc.layout
- docs/MOM_parameter_doc.short
https://github.com/COSIMA/access-om3/issues/174
> Manually add auto-generated MOM_parameter_doc.* for comprehensive documentation

- MOM_input
- docs/MOM_parameter_doc.all
See https://github.com/COSIMA/access-om3/issues/177
> [0.25deg] Update MINIMUM_DEPTH & MASKING_DEPTH IN MOM_grid_init

- nuopc.runconfig
https://github.com/COSIMA/access-om3/issues/157 (#95)
Cherry-pick from https://github.com/COSIMA/MOM6-CICE6/pull/95
> Add comments after ocn_cpl_dt in nuopc.runconfig

- config.yaml
- nuopc.runconfig
See https://github.com/COSIMA/access-om3/issues/130#issuecomment-2301146030
> `1deg_jra55do_ryf`: update PE layout

- ice_in
See https://github.com/COSIMA/access-om3/issues/210
> Update cice blocks to suit the new PE layout

- MOM_input
- docs/MOM_parameter_doc.all
See https://github.com/COSIMA/access-om3/issues/137
> set DIABATIC_FIRST to False by default.

- config.yaml
- datm.streams.xml
- datm_in
- drof.streams.xml
- manifests/exe.yaml
- manifests/input.yaml
Companion to https://github.com/ACCESS-NRI/access-om3-configs/pull/123
> Dev 1deg jra55do iaf iss208

- config.yaml
- datm.streams.xml
- datm_in
- drof.streams.xml
- manifests/exe.yaml
- manifests/input.yaml
> Cherry pick from pr123 into dev 1deg jra55do ryf wombatlite

- config.yaml
- datm.streams.xml
- datm_in
- drof.streams.xml
- manifests/exe.yaml
- manifests/input.yaml
Companion PR to https://github.com/ACCESS-NRI/access-om3-configs/pull/123
> Cherry pick from pr123 into dev 025deg jra55do ryf

- config.yaml
- manifests/exe.yaml
Companion to #124 
contributes to https://github.com/COSIMA/access-om3/issues/194 and https://github.com/COSIMA/access-om3/issues/228
> Move to NRI Spack Build

- MOM_input
Contributes to https://github.com/COSIMA/access-om3/issues/233
> Remove channel config

- config/ci.json
Update to the last model config tests version
> Update to model config test 0.0.9

- ice_in
See https://github.com/COSIMA/access-om3/issues/287
> Use agreed-upon convention for CICE output filenames

- config/ci.json
Add's release config into config.yaml for future proofing
closes #193
> Use regex for scheduled tests

- README.md
- config/ci.json
This PR updates includes a few updates following the consolidation of MC and MCW configuration branches
Closes #477
> Updates following consolidation of MC and MCW branches

- config.yaml
- docs/MOM_parameter_doc.layout
- ice_in
- manifests/exe.yaml
- manifests/input.yaml
- testing/checksum/historical-3hr-checksum.json
Companion PR to #481 
- **update MOM_parameter_doc.layout**
- **Update to 2025.01.2 and use MOM hgrid in cice**
> 452 dev MC 1deg jra iaf

- config.yaml
- docs/MOM_parameter_doc.layout
- ice_in
- manifests/exe.yaml
- manifests/input.yaml
- testing/checksum/historical-3hr-checksum.json
Companion PR to #481 
- **update MOM_parameter_doc.layout**
- **Update to 2025.01.2 and use MOM hgrid in cice**
> 452 dev MC 1deg jra ryf+wombatlite

- config.yaml
- docs/available_diags.000000
- ice_in
- manifests/exe.yaml
- manifests/input.yaml
- testing/checksum/historical-3hr-checksum.json
Companion PR to #481 
- **update MOM_parameter_doc.layout**
- **Update to 2025.01.2 and use MOM hgrid in cice**
> Update to 2025.01.2 and use MOM hgrid in cice

- diag_table
- diag_table_source.yaml
- docs/available_diags.000000
- input.nml
Cherry-pick diag_table changes from https://github.com/ACCESS-NRI/access-om3-configs/pull/157
- https://github.com/ACCESS-NRI/access-om3-configs/issues/438
> Cherry-pick diag_table to dev-MC_1deg_jra_ryf

- config/ci.json
Turns on restart and repeat repro tests on `dev-MC_1deg_jra_ryf+wombatlite`
Closes #492
> Turn on restart and repeat repro tests on `dev-MC_1deg_jra_ryf+wombatlite`

- README.md
- config/ci.json
I've updated our branch names following #500. This PR updates the `ci.json` and `README.md` accordingly
Closes #500
> Updates for new branch names

- README.md
> link to documentation in README.md

- nuopc.runseq
Run sequence in `nuopc.runseq`
Achieves further performance improvements over 90cd050 without changing answers.
- https://github.com/ACCESS-NRI/access-om3-configs/pull/577
- https://github.com/ACCESS-NRI/access-om3-configs/issues/575
A PR has been created for updating the …
> Modify nuopc.runseq to improve performance

- MOM_input
- config.yaml
- docs/MOM_parameter_doc.layout
- ice_in
- nuopc.runconfig
- testing/checksum/historical-3hr-checksum.json
changing from cascadelake queue (normal) -> SappireRapids (normalsr)
cpu cores for each component and total cpu cores for the 25km configuration.
Adding one parameter `AUTO_IO_LAYOUT_FAC` in MOM_input to enable io layout
Updaing `block_size_x` and `block_size_y` in ice_in to ensure a better performance of CICE under current layout
Improve loading balancing along with https://github.com/ACCESS-NRI/access-om3-configs/pull/589
Improve runtime from 20733.7269 seconds (5:46) to 10869.96992 seconds (3:01) by only adding another 244 cores.
- https://github.com/ACCESS-NRI/access-om3-configs/issues/334
This change requires changes to (note required version where …
> Tune processor and MOM I/O layout for the 25km configuration

- config.yaml
- datm_in
- drof_in
- ice_in
- manifests/exe.yaml
- manifests/input.yaml
- nuopc.runconfig
- nuopc.runseq
- testing/checksum/historical-3hr-checksum.json
> 547 dev mc 25km jra ryf

- documentation/docs/pages/Grids.md
> Update Grids.md for new cice grid output file

- config.yaml
- manifests/input.yaml
- testing/checksum/historical-3hr-checksum.json
This PR updates the MOM6 initial condition and salinity restoring files with proper metadata, provenance and addresses issue [580](https://github.com/ACCESS-NRI/access-om3-configs/issues/580).
https://github.com/ACCESS-NRI/access-om3-configs/issues/344
https://github.com/ACCESS-NRI/access-om3-configs/issues/580
Yes, test runs are fine.
A PR has been created for updating the documentation?
**8. Formatting**
Changes to MOM_input have been copied from model output in docs/MOM_parameter_docs.short?
> Update initial conditions and salinity restoring files

- config.yaml
- datm.streams.xml
- drof.streams.xml
- manifests/input.yaml
- testing/checksum/historical-3hr-checksum.json
Moved to JRAv1.6 and fixed time offsets per https://github.com/ACCESS-NRI/access-om3-configs/issues/437
- #437 
- #387 
Uses [latest](https://github.com/ACCESS-NRI/om3-scripts/commit/ffad24e7448649c5797bffe6a4e6184741dd87a5) from om3-scripts to make a stream file
Ran for one-year without crashing.
A PR has been created …
> Update stream files for correct offset and JRA55do v1.6 

- .github/workflows/schedule.yml
- config/ci.json
Update scheduled tests to run over the weekend, to include 25km release config and latest version of model-config-tests
contributes to #572
> Update CI pre-release

- config.yaml
- datm.streams.xml
- drof.streams.xml
- manifests/input.yaml
- testing/checksum/historical-3hr-checksum.json
> Cherry pick from pr616 into dev mc 25km jra ryf

- config.yaml
- datm.streams.xml
- drof.streams.xml
- manifests/input.yaml
- testing/checksum/historical-3hr-checksum.json
> Cherry pick from pr616 into dev mc 100km jra ryf+wombatlite

- config.yaml
- datm.streams.xml
- drof.streams.xml
- manifests/input.yaml
- testing/checksum/historical-3hr-checksum.json
> Cherry pick from pr628 into dev mc 25km jra ryf+wombatlite

- README.md
As discussed at this morning's OSIT, just re-directing to the how to run doc'.
> Update README.md for how to run for the om3 25km beta release

- config.yaml
Moved concatenation of daily data and intake datastore generation to post script
This reduced the resources needed ( as postscript is a separate PBS job, whilst archive uses all the model resources).
- #501 
https://github.com/ACCESS-NRI/om3-scripts/pull/69
Removes dependency on nco
See automated testing in https://github.com/ACCESS-NRI/om3-scripts/pull/69, and ran with two years of 25km output to confirm the postscript runs to completion and concatenates daily data.
**5. CI …
> Move cice concatenation of daily data and intake datastore generation to postscript

- metadata.yaml
Set version for release (see https://github.com/ACCESS-NRI/access-om3-configs/pull/652#issuecomment-3105479518)
> Set version for release

- documentation/docs/pages/Topography-generation.md
This PR updates the `Topography-generation.md` documentation to include the steps to update the restart files when the bathymetry is updated.
https://github.com/ACCESS-NRI/access-om3-configs/issues/502
> Add documentation on updating restart files

- CITATION.cff
Add a CITATION.cff per #650 
@aidanheerdegen @tmcadam - shall we go ahead with this?
It needs a correct DOI and an correct author list
> Create CITATION.cff for 25km ryf 1.0 beta

- config/ci.json
Companion change to https://github.com/ACCESS-NRI/access-om3-configs/pull/659
> Update ci.json to set payu minimum version

- config/ci.json
Model config tests with 0.2.1 (with https://github.com/ACCESS-NRI/model-config-tests/commit/bd66b6b4b55d69b18f54a79f56d785748bcb012b and https://github.com/ACCESS-NRI/model-config-tests/commit/2d000c586ef2340ffdb62f21b31527539147aeed)
> Update ci.json for model-config-tests 0.2.1

- documentation/docs/index.md
For @atteggiani to add some magic.
> For @atteggiani to add a button towards how to run doc.

- ice_in
- testing/checksum/historical-3hr-checksum.json
Changed sea ice cold start initial conditions from default to none
Default starts with too much sea ice and is confusing
- #661 
None :)
Ran for ~4 years - sea ice volume caught up ok - see https://github.com/ACCESS-NRI/access-om3-configs/issues/661#issuecomment-3134423811
A PR has been created for updating the documentation?
**8. Formatting**
Changes to MOM_input have been copied from model output in …
> Set ice_ic to none

- README.md
- metadata.yaml
Contributes to #716 
Some corrections to the release-branch, doesn't affect the model at all.
> Fix Readme and Metadata in release-MC_25km

- MOM_input
- README.md
- config.yaml
- diagnostic_profiles/diag_table_standard
- diagnostic_profiles/source_yaml_files/diag_table_standard_source.yaml
- docs/MOM_parameter_doc.all
- docs/MOM_parameter_doc.layout
- docs/MOM_parameter_doc.short
- docs/available_diags.000000
- manifests/exe.yaml
- metadata.yaml
- testing/checksum/historical-6hr-checksum.json
This updates all upstream components for up to date bug fixes and features. This updates to compiler oneapi 2025.02.000
- #632 
- #436 
Our current config runs fine with the new exectuable. As I set ocean_geometry filename, ill mark this as dependent on the access-om3 2025.08.001 deployment.
See https://github.com/ACCESS-NRI/access-om3-configs/issues/730#issuecomment-3235977769
Global sums of T&S are unchanged
Is this reproducible with the previous commit? (If not, why …
> Use 2025.08.001 deployment

- MOM_input
- config.yaml
- diagnostic_profiles/diag_table_standard
- diagnostic_profiles/source_yaml_files/diag_table_standard_source.yaml
- docs/MOM_parameter_doc.all
- docs/MOM_parameter_doc.layout
- docs/MOM_parameter_doc.short
- docs/available_diags.000000
- manifests/exe.yaml
- testing/checksum/historical-6hr-checksum.json
Cherry-pick updates to model build - contributes to #632 
Was run for RYF, not for this branch - see #747
> Sync 25km IAF branch with new build

- MOM_input
- config.yaml
- docs/MOM_parameter_doc.all
- docs/MOM_parameter_doc.short
- docs/available_diags.000000
- manifests/input.yaml
- testing/checksum/historical-6hr-checksum.json
This PR implements the following changes from the 25km configs in `dev-MC_100km_jra_ryf`:
- Update to WOA23 initial conditions and restoring with correct salinity (https://github.com/ACCESS-NRI/access-om3-configs/pull/610 and https://github.com/ACCESS-NRI/access-om3-configs/pull/725)
- Change EOS and prognostic temp/salt (https://github.com/ACCESS-NRI/access-om3-configs/pull/641)
- https://github.com/ACCESS-NRI/access-om3-configs/issues/771#issuecomment-3310434280
Is this …
> 100km RYF: Change EOS and prognostic temp/salt and update to WOA23 ICs and restoring
