ACCESS-NRI/access-om3-configs

- archive_cice_restarts.sh
- config.yaml
- ice_in
- nuopc.runconfig
- setup_cice_restarts.sh
As part of https://github.com/COSIMA/access-om3/issues/81, it was identified that there is a bug with symlink handling with parallel reads in openmpi (https://github.com/open-mpi/ompi/issues/12141). The fix for the bug will be included in OpenMpi 4.1.7 but this may not be released until end of March 2024. This bug blocks use of netcdf4 in CICE.
In the interim, we can patch this bug using the two scripts in this PR, which replace the symlink to the initial conditions with a copy of the initial conditions file and replace the symlink to restart files with a hardlink to restart files. (We can't rely on hardlinking to the initial conditions file because it may not be on the same file system as where the model is being run from.)
This allows turning on netcdf4 support in CICE (in …
> Symlink patch & CICE netcdf4 parrallel

- datm.streams.xml
- drof.streams.xml
- generate_xml_datm.py
- generate_xml_drof.py
Turn off cycling around forcing data for iaf runs. #22
> limit valid years to 1958 to 2018

- config.yaml
- fd.yaml
- manifests/exe.yaml
Changes needed to use latest OM3 executable.
Contributes to https://github.com/COSIMA/access-om3/issues/118
> 1deg_jra55do_iaf: update OM3 executable to latest version

- config.yaml
- fd.yaml
- manifests/exe.yaml
Changes needed to use latest OM3 executable.
Contributes to https://github.com/COSIMA/access-om3/issues/118
> 1deg_jra55do_ryf: update OM3 executable to latest version

- MOM_input
- README.md
- config.yaml
- datm_in
- drof_in
- ice_in
- manifests/input.yaml
- nuopc.runconfig
- nuopc.runseq
This pull request addresses the upgrade of the 1-Degree RYF configuration to a higher resolution of 0.25-Degree RYF configuration. 
Changes Implemented:
1. A new CICE grid has been generated from the MOM super grid to resolve the longitude mismatch issue in these PRs [1](https://github.com/COSIMA/om3-scripts/pull/6) and [2](https://github.com/COSIMA/om3-scripts/pull/8)
2. The CFL violation error caused by bad departure points has been fixed by adjusting the time step of CICE and MOM, similar to OM2 quarter-degree configurations. Note that only the time step has been changed and `ndtd` is not changed to avoid truncation errors in MOM6 [refer here](https://github.com/COSIMA/MOM6-CICE6/commit/96eebce8d2e7256cae053a94feac602ad66c9770).
3. Fixed Restart File Issue: Multiple restart files were …
> Upgrade 1-Degree to 025-Degree RYF Configuration

- config.yaml
- manifests/input.yaml
This PR updates all the input paths to the new locations in `vk83`. Contributes to https://github.com/COSIMA/access-om3/issues/162
> Update input paths to `vk83`: `1deg_jra55do_ryf`

- config.yaml
- manifests/input.yaml
- setup_cice_restarts.sh
This PR updates all the input paths to the new locations in `vk83`. Contributes to https://github.com/COSIMA/access-om3/issues/162
> Update input paths to `vk83`: `025deg_jra55do_ryf`

- MOM_input
- config.yaml
- ice_in
- manifests/input.yaml
- nuopc.runconfig
Changes described in https://github.com/COSIMA/access-om3/issues/113 for move to CICE 6.5. Uncompressed daily history output is 15MB, compressed is 2MB.
Add new cice grid from https://github.com/COSIMA/esmgrids/pull/6 and (https://github.com/COSIMA/access-om2/issues/279 )
Tigthen grid angle check limits (per https://github.com/COSIMA/access-om3/issues/144)
Add freeboard as a default history output to make validation easier.
Turn off metadata for development work.
Change should be described in each commit, I will not squash the commits.
> CICE config for CICE6.5

- MOM_input
- config.yaml
- ice_in
- manifests/input.yaml
- nuopc.runconfig
Changes described in https://github.com/COSIMA/access-om3/issues/113 for move to CICE 6.5. Uncompressed daily history output is 15MB, compressed is 2MB.
Add new cice grid from https://github.com/COSIMA/esmgrids/pull/6 and (https://github.com/COSIMA/access-om2/issues/279 )
Tigthen grid angle check limits (per https://github.com/COSIMA/access-om3/issues/144)
Add freeboard as a default history output to make validation easier.
Turn off metadata for development work.
Changes should be described in each commit, I will not squash the commits.
> 025deg jra55do ryf.iss113

- MOM_input
- config.yaml
- ice_in
- manifests/input.yaml
- nuopc.runconfig
Changes described in https://github.com/COSIMA/access-om3/issues/113 for move to CICE 6.5. Uncompressed daily history output is 15MB, compressed is 2MB.
Add new cice grid from https://github.com/COSIMA/esmgrids/pull/6 and (https://github.com/COSIMA/access-om2/issues/279 )
Tigthen grid angle check limits (per https://github.com/COSIMA/access-om3/issues/144)
Add freeboard as a default history output to make validation easier.
Turn off metadata for development work.
Change should be described in each commit, I will not squash the commits.
> 1deg jra55do ryf.iss113

- MOM_input
Unsets `MAX_DELTA_SRESTORE` in `MOM_input` so that it takes the default `MAX_DELTA_SRESTORE = 999.0`. See https://github.com/COSIMA/access-om3/issues/167
> Unset `MAX_DELTA_SRESTORE`: `1deg_jra55do_iaf`

- MOM_input
Unsets `MAX_DELTA_SRESTORE` in MOM_input so that it takes the default `MAX_DELTA_SRESTORE = 999.0`. See https://github.com/COSIMA/access-om3/issues/167
> Unset `MAX_DELTA_SRESTORE`: `025deg_jra55do_ryf`

- MOM_input
Unsets `MAX_DELTA_SRESTORE` in MOM_input so that it takes the default `MAX_DELTA_SRESTORE = 999.0`. See https://github.com/COSIMA/access-om3/issues/167
> Unset `MAX_DELTA_SRESTORE`: `1deg_jra55do_ryf`

- nuopc.runconfig
This PR address [#132](https://github.com/COSIMA/access-om3/issues/132) by setting meaningless values for `{model_name}_cpl_dt` in `nuopc.runconfig` .
> Meaningless values for {model_name}_cpl_dt in nuopc.runconfig 1deg_jra55do_iaf

- nuopc.runconfig
This PR address [#132](https://github.com/COSIMA/access-om3/issues/132) by setting meaningless values for `{model_name}_cpl_dt` in nuopc.runconfig .
> Meaningless values for {model_name}_cpl_dt in nuopc.runconfig 1deg_jra55do_ryf

- MOM_input
- docs/MOM_parameter_doc.all
Disable `TIDES` and associated parameters. One thing to note: we might need to add the `INT_TIDE_DISSIPATION` parameter to parameterise the turbulent mixing generated by breaking internal waves for local dissipation. To do this, `tideamp.nc`, which contains the averaged tidal flow amplitudes must be included in the input files.
See https://github.com/COSIMA/access-om3/issues/176
> [0.25deg] Disable TIDES and associated parameters

- nuopc.runconfig
This PR address https://github.com/COSIMA/access-om3/issues/132 by setting meaningless values for {model_name}_cpl_dt in nuopc.runconfig .
> Meaningless values for {model_name}_cpl_dt in nuopc.runconfig

- config.yaml
- manifests/exe.yaml
This PR updates the ACCESS-OM3 executable to include recent code changes. See https://github.com/COSIMA/access-om3/issues/183
> Update to latest ACCESS-OM3 executable: `025deg_jra55do_ryf`

- config.yaml
- manifests/exe.yaml
This PR updates the ACCESS-OM3 executable to include recent code changes. See https://github.com/COSIMA/access-om3/issues/183
> Update to latest ACCESS-OM3 executable: `1deg_jra55do_iaf`

- config.yaml
- manifests/exe.yaml
This PR updates the ACCESS-OM3 executable to include recent code changes. See https://github.com/COSIMA/access-om3/issues/183
> Update to latest ACCESS-OM3 executable: `1deg_jra55do_ryf`

- MOM_input
- docs/MOM_parameter_doc.layout
to automatically generate a mask table to exclude land masks.
See https://github.com/COSIMA/access-om3/issues/184
> Turn on AUTO_MASKTABLE 

- .github/workflows/automatic-cherry-pick.yaml
This workflow allows to cherry-pick commits from a PR into a list of target  branches. A new PR will be created for each target branch. This is triggered by a comment on the pull request of the following form:
`cherry-pick <hash_1> <hash_2> ... <hash_n> into <branch_1> <branch_2> ... <branch_n>`
Planned/missing features:
- cherry-picking into a different git repo (e.g. `cherry-pick abcd into MOM6-CICE6-WW3/1deg_jra55do_ryf`
- wildcards in repos/branches (e.g. `cherry-pick abcd into MOM6-CICE6-WW3/*`
- multiple commands in a single comment
Contributes to https://github.com/COSIMA/access-om3/issues/119
> Add automatic cherry-pick workflow

- MOM_input
- config.yaml
- nuopc.runconfig
- nuopc.runseq
use DT_THERM=6*DT and DIABATIC_FIRST = False - see https://github.com/COSIMA/ACCESS-OM3/issues/138
> DT_THERM=6*DT and DIABATIC_FIRST = False

- nuopc.runconfig
See https://github.com/COSIMA/access-om3/issues/157, https://github.com/COSIMA/access-om3/issues/157#issuecomment-2249623984
> Add comments after ocn_cpl_dt in nuopc.runconfig 

- nuopc.runconfig
Fix bug caused by the equal sign '=' from comments (after '#')
```
...
72 [gadi-cpu-clx-0238:1008973:0:1008973] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x65d8)
73 [gadi-cpu-clx-0238:1008975:0:1008975] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x65d8)
74 ==== backtrace (tid:1008976) ====
75  0 0x0000000000012d20 __funlockfile()  :0
76  1 0x0000000002e01faf mom_mp_mom_state_is_synchronized_()  /jobfs/121983958.gadi-pbs/ds0092/spack-stage/spack-stage-access-om3-63ed4a4777aeac0c6     2720ddbe7f85e4ed16f82eb_main-xekfuu46z2ztbywtak2u3oenjedrynn4/spack-src/MOM6/MOM6/src/core/MOM.F90:3861
77  2 0x0000000002d749df mom_ocean_model_nuopc_mp_ocean_model_restart_()  /jobfs/121983958.gadi-pbs/ds0092/spack-stage/spack-stage-access …
```
> Fix bug in nuopc.runconfig by removing the equal sign ('=') from comments (after '#')

- nuopc.runconfig
Cherry-pick from https://github.com/COSIMA/MOM6-CICE6/pull/98
> Fix bug in nuopc.runconfig by removing the equal sign ('=') from comments (after '#') (#98)

- MOM_input
- nuopc.runconfig
- nuopc.runseq
In #94, untested changes were made to MOM6 parameter `DT_THERM` and related parameters. This PR reverts those changes until testing has been done and a suitable value of `DT_THERM` has been determined.
> `1deg_jra55do_ryf`: Revert #94 (use `DT_THERM=6*DT` and `DIABATIC_FIRST = False`)

- nuopc.runconfig
https://github.com/COSIMA/MOM6-CICE6/pull/97 changed the value of `ocn_cpl_dt` in the `nuopc.runconfig` to be inconsistent with the `nuopc.runseq`. This PR fixes it.
> `1deg_jra55do_iaf`: Fix incorrect `ocn_cpl_dt` in `nuopc.runconfig`

- config.yaml
- ice_in
- nuopc.runconfig
See https://github.com/COSIMA/access-om3/issues/214
> [0.25deg] Update PE layout

- doc/MOM_input
- doc/README_doc.md
- doc/config.yaml
- doc/ice_in
- doc/nuopc.runconfig
- doc/nuopc.runseq
contributes to https://github.com/COSIMA/access-om3/issues/224
> update doc files

- .github/workflows/generate-initial-checksums.yml
- README.md
- config/ci.json
Initial set up for user-dispatchable repro ci tests. For info on the `config/ci.json` file, see https://github.com/ACCESS-NRI/model-configs-template?tab=readme-ov-file#in-configcijson
In this PR:
- **Added initial ci.json configuration file**
- **Added initial checksum generation workflow**
- **Updated README.md to refer to the above new things**
Repository Changes:
- Added Repo-level `vars.CI_JSON_SCHEMA_VERSION`
- Added `"Gadi Initial Checksum"` Environment and the required `vars`/`secrets`. Also added `ACCESS-NRI/ocean` team as required reviewer
Closes #120
> Add User-Dispatchable Repro Tests

- config.yaml
- datm.streams.xml
- datm_in
- drof.streams.xml
- manifests/exe.yaml
- manifests/input.yaml
This PR replaces https://github.com/ACCESS-NRI/access-om3-configs/pull/113.
When cherry-picked to other branches, this will addresses
https://github.com/COSIMA/access-om3/issues/208
https://github.com/COSIMA/om3-scripts/issues/27
https://github.com/COSIMA/om3-scripts/issues/29
Separate commits  are used to facilitate the differing PRs needed for different configs (e.g. IAF).
> fix JRA55do inputs

- config.yaml
- manifests/exe.yaml
Move to nri-spack build. This is using the same access-om3 code and dependencies as the cosima-spack, although some build settings are different (e.g. the 'target' attribute). Its possible the performance is slightly different with this build.
The build still uses https://github.com/COSIMA/access-om3 for model components
> Move to nri-spack

- .github/workflows/ci.yml
- .github/workflows/config.yml
- CONTRIBUTING.md
- README.md
This PR is a slimmed-down variant of the now-closed #122 PR. 
This PR contains only the base workflow as specified in `access-nri/model-configs-template`, similar to the existing `access-[om2|esm1.5]-configs` repositories. This is so we can merge in functionality that is set in stone, with additions that require extra time/thought to come later. 
References #120
> Base PR-Based Repro-Testing Workflow 

- .github/workflows/ci.yml
This PR introduces a PR comment-command of the form:
```
!test repro [commit]
```
which runs a repro test comparing the `HEAD` of the source (PR)  branch against the last common ancestor of the target (merged-into) branch, and optionally commits the result to the PR that the comment was found in. 
This allows repro checks to be run on any branch, rather than just being automatically run on `dev-*` -> `release-*` PRs. 
Appropriate safeguards have been taken so that the comment command will only work for users who have `write`/`admin` permissions on the PR they are commenting on. 
In this PR:
- **Add in job to handle `!test` comment commands**
Requires ACCESS-NRI/model-config-tests#73
References #120
> `!test` Comment Command

- .github/workflows/ci.yml
In this PR, we quote the `!test` Job Name because `!` is a reserved character in yaml that is making the workflow fail to start.
> Quoted '!test' job name

- .github/workflows/ci.yml
In this PR, we add the `.github/workflows/ci.yml` file at `main` (specifically https://github.com/ACCESS-NRI/access-om3-configs/tree/a30ee6171164820efdfa50275620288f60465dbc/.github/workflows/ci.yml) to `dev-025deg_jra55do_ryf`. 
References #138
> Migrate CI onto `dev-025deg_jra55do_ryf`

- .github/workflows/ci.yml
In this PR, we add the `.github/workflows/ci.yml` file at `main` (specifically https://github.com/ACCESS-NRI/access-om3-configs/tree/a30ee6171164820efdfa50275620288f60465dbc/.github/workflows/ci.yml) to `dev-1deg_jra55do_ryf_wombatlite`. 
References #138
> Migrate CI onto `dev-1deg_jra55do_ryf_wombatlite`

- .github/workflows/ci.yml
In this PR, we add the `.github/workflows/ci.yml` file at `main` (specifically https://github.com/ACCESS-NRI/access-om3-configs/tree/a30ee6171164820efdfa50275620288f60465dbc/.github/workflows/ci.yml) to `dev-1deg_jra55do_iaf`. 
References #138
> Migrate CI onto `dev-1deg_jra55do_iaf`

- MOM_input
Unset Channel_config per https://github.com/COSIMA/access-om3/issues/233
> Remove unused channel config parameter

- config/ci.json
Per #162, turn off config CI tests until these configurations are further developed.
This will allow progress on issues like https://github.com/ACCESS-NRI/access-om3-configs/pull/157
> Turn-off config CI checks until configs are further developed

- config/ci.json
A fix has been added to `model-config-tests` to address https://github.com/COSIMA/access-om3/issues/265. This PR updates the version of `model-config-tests` used by the CI to include the fix.
> Update model-config-tests version

- .github/workflows/generate-initial-checksums.yml
See failed run https://github.com/ACCESS-NRI/access-om3-configs/actions/runs/13254576757
This is due to the [updated structure](https://github.com/ACCESS-NRI/model-config-tests/pull/77) of `model-config-tests` requiring `checks: write` when it didn't need to before. This was missed in the linked PR. 
This PR adds `checks: write` to the entrypoint workflow, as required.
> Added 'checks: write' to model-configs-tests initial-checksums entrypoint

- .github/workflows/schedule.yml
I'd realised that `access-om3-configs` doesn't actually have the `schedule.yml` workflow, so scheduled checks wouldn't run. 
This PR adds scheduled monthly repro checks for `access-om3-configs`, given there are entries in `configs/ci.json`.
> Add Scheduled Checks Workflow

- MOM_input
- docs/MOM_parameter_doc.all
- docs/MOM_parameter_doc.debugging
- docs/MOM_parameter_doc.layout
- docs/MOM_parameter_doc.short
Changes in this PR:
- A bunch of MOM6 parameter changes - see https://github.com/COSIMA/access-om3/issues/274.
- ~Reverts to using the old CICE grid file, rather than the MOM supergrid - see https://github.com/COSIMA/access-om3/issues/275.~ - see [comment below](https://github.com/ACCESS-NRI/access-om3-configs/pull/176#issuecomment-2664173399)
- Adds up-to-date `MOM_parameter_doc.*` files.
> Additional MOM6 parameter changes for 0.4.0

- config/ci.json
This turns on two tests for the 1deg ryf branch.
One is that 2x1day runs give the same results as 1x2day run.
One is that 2x1days results from the same initial conditions give the same result.
Contributes to #41 
I have triggered the `checksum_slow` tests manually on gadi to confirm they run.
> Turn on restart reproducability for 1deg ryf

- .github/workflows/schedule.yml
- config/ci.json
Closes #193 and #162 
@jo-basevi : if you can check syntactical correctness that would be great. also, can we use payu main branch or does it have to be a tagged version ?
@dougiesquire : we could make a special condition to run restart repro on specific test branches if desired ? (e.g. for all branches which contain the word repro ?)
> Update ci config

- config.yaml
- manifests/exe.yaml
- testing/checksum/historical-3hr-checksum.json
This PR updates to ACCESS-OM3 2025.01.1 which:
- Reverts MOM to non-symmetric mode
- Compiles ESMF with `fp-model precise`
https://github.com/COSIMA/access-om3/issues/299
The expectation is that this will fail the historical repro test, but will pass the repeat and restart repro tests. UPDATE: expectation [confirmed by repro tests](https://github.com/ACCESS-NRI/access-om3-configs/pull/214#issuecomment-2712785869)
> Update to ACCESS-OM3 2025.01.1

- MOM_input
- docs/MOM_parameter_doc.all
- docs/MOM_parameter_doc.short
- nuopc.runconfig
- nuopc.runseq
- testing/checksum/historical-3hr-checksum.json
The PR updates ocean dynamic, tracer timesteps along with coupling timestep. 
- https://github.com/COSIMA/access-om3/issues/138
**3. Documentation**
- With the current timestep setup, running performance has significantly improved, especially for MOM6, making it comparable to MOM5 when using a similar number of CPU cores over a 10-day run (without diagnostics). However, the total runtime is not fully optimised due to load imbalance in the NUOPC coupling. This will be addressed later in another PR. 
- Additional documentation and details can be found under current PR: https://github.com/ACCESS-NRI/access-om3-configs/pull/223#issuecomment-2739379301
> Update baroclinic, thermodynamic, coupling timesteps

- config.yaml
- docs/MOM_parameter_doc.layout
- ice_in
- manifests/exe.yaml
- manifests/input.yaml
- testing/checksum/historical-3hr-checksum.json
This fixes a small bug in the implementation of loading the mom hgrid file in CICE and turns on using this feature in the CICE configuration.
#452 
Needs access-om3 deployment 2025.01.2
Ran for 1 year with no truncations
Will trigger below
No - build doesn't change answers but changing the grid does changes answers
We should update the "grids" subsection in the old wiki - @chrisb13 - is there a documentation branch where this change should go ?
**8. Formatting**
I think i remember to update manifests, no changes to MOM_input/parameter docs.
Merge commit
> Turn on mom supergrid in  dev mc 1deg jra ryf

- diag_table
- diag_table_source.yaml
- docs/available_diags.000000
- input.nml
Cherry-pick diag_table changes from https://github.com/ACCESS-NRI/access-om3-configs/pull/157
- https://github.com/ACCESS-NRI/access-om3-configs/issues/438
**3. Ad-hoc Testing**
`FATAL from PE     0: diag_manager_mod::init_field_cell_measures: VOLUME measures field "ocean_model/volcello" NOT in diag_table with correct output frequency for field ocean_model/diftrblo`
---
Include wombatlite specific diagnostics as well.
> Cherry-pick diag_table to dev-MC_1deg_jra_ryf+wombatlite

- diag_table
- diag_table_source.yaml
- docs/available_diags.000000
Updated the MOM diagnostic table configuration to output annual files instead of one file per month.
- https://github.com/ACCESS-NRI/access-om3-configs/issues/498
> Reduce MOM diagnostic output frequency to annual files

- config.yaml
- datm_in
- drof_in
- ice_in
- input.nml
- manifests/exe.yaml
- manifests/input.yaml
- nuopc.runconfig
- nuopc.runseq
- testing/checksum/historical-3hr-checksum.json
Moved to the latest build, removed an unused config line and updated degrees to km in the input files. Updated the run sequence to be more efficient, turned on cice grid output.
This moves to a oneapi build, and spack packages build seperately for each model component
- See linked issues in commits
A 12-month run before and after the change most global averages look unchanged (e.g.) :
With the exception of salt added in the ocean_scalar file:
But I think that's dodgy accounting / hitting the precision limit of double vars, as comparing the other two salt flux fields …
> Use 2025.05.000/1 build using oneapi compiler

- MOM_input
- docs/MOM_parameter_doc.all
- docs/MOM_parameter_doc.debugging
- docs/MOM_parameter_doc.short
- docs/available_diags.000000
- nuopc.runconfig
- nuopc.runseq
- testing/checksum/historical-3hr-checksum.json
Update `MOM_input` parameters to closely follow the latest settings from [GFDL OM5](https://github.com/breichl/MOM6-examples/blob/3258cc63fc03776e33929aa03c3bb644b40fec97/ice_ocean_SIS2/Baltic_OM5_025/MOM_parameter_doc.all), which have been shown to support stable long-term runs.
1. Most parameters in `MOM_input`
2. coupling timestep in `nuopc.runseq`
3. ocn_cpl_dt in `nuopc.runconfig`
4. All doc files in `docs`
stable long-term control runs without truncation errors.
- https://github.com/ACCESS-NRI/access-om3-configs/issues/555
What ad-hoc testing was done? How are …
> Parameter updates for improved stability in 25 km configuration

- testing/checksum/historical-3hr-checksum.json
This is a follow-up PR to update checksums for https://github.com/ACCESS-NRI/access-om3-configs/pull/562
-
A PR has been created for updating the documentation?
**8. Formatting**
Changes to MOM_input have been copied from model output in docs/MOM_parameter_docs.short?
> Update checksums for tidal dissipation

- README.md
This PR adds the new `dev-MC_25km_jra_ryf+wombatlite` to the README. To prevent the list of comparison quick-links getting too long, I've also remove some comparisons that are less useful.
Closes #618
> Add `dev-MC_25km_jra_ryf+wombatlite` branch to README

- config.yaml
Updating the payu minimum version.
1.17 includes date base restart pruning, and automated committing of MOM_paramater_doc files (https://github.com/payu-org/payu/releases/tag/1.1.7)
> Set payu minimum version

- documentation/mkdocs.yml
- documentation/requirements.txt
@minghangli-uni 
Added `csl_file` option to bibtex plugin to style citations. 
The csl_file is taken from the [apa.csl](https://raw.githubusercontent.com/citation-style-language/styles/26eccff9e537f71494a4da7b91afac1adf571dc9/apa.csl), which is a "Author-Date" format CSL.
This means that citations written as:
```markdown
[@citation-key]
```
Will be rendered as:
> (FIRST-AUTHOR et al., YEAR) <sup>1</sup>
instead of the previous:
> <sup>1</sup>
> Style citations

- data_table
This PR adds a `data_table` with fields for co2 and o2 fluxes.
@helenmacdonald I recall Lizzie has already created the dust input on the correct grid? Do you have access to Lizzie’s dust file and if so can you add it?
You'll need to add the path to the file to the `config.yaml` and the following to the `data_table`:
```
"OCN", "dry_dep_fe_flux_ice_ocn", "dust", "./INPUT/dust.nc", "none", -1.0e-06
```
If it's not ready to go, we could just merge this and add dust forcing later
> Add data_table with fields for co2 and o2 fluxes

- config.yaml
- data_table
New dust forcing file is generated using https://github.com/ACCESS-NRI/om3-scripts/blob/main/wombat_ic_generation/regrid_forcing.py
```
$ module use /g/data/xp65/public/modules
$ module load conda/analysis3-25.06
$ python3 /g/data/vk83/apps/om3-scripts/wombat_ic_generation/regrid_forcing.py --forcing-filename=/g/data/ik11/inputs/BGC/input/dust.nc --hgrid-filename=/g/data/ol01/ee8016/regional_wombat/hgrid.nc --output-filename=/g/data/ol01/ee8016/regional_wombat/modifiedfiles/dust_DS.nc --mask-filename=/g/data/ik11/inputs/BGC/input/dust_mask.nc --lon-name=x_T --lat-name=y_T
```
> Add dust forcing to data_table

- documentation/mkdocs.yml
- documentation/requirements.txt
https://github.com/ACCESS-NRI/access-om3-configs/blob/f5576932a5300585ef050b1c5cba2f9596390631/documentation/mkdocs.yml#L57-L70
The plugin settings will need adjustments, so we should discuss below what are the correct settings based on your needs.
For details, please read the [mkdocs-include-configuration-stubs-plugin documentation](https://github.com/ACCESS-NRI/mkdocs_include_configuration_stubs_plugin?tab=readme-ov-file#mkdocs-include-configuration-stubs-plugin) and please let me know if any part is missing or unclear.
Currently writing more content in the [MkDocs Wrapper section](https://github.com/ACCESS-NRI/mkdocs_include_configuration_stubs_plugin?tab=readme-ov-file#mkdocs-wrapper).
> [!CAUTION]
> As long as this PR is not merged (or closed), other PR previews will not work (this …
> Include stubs

- config.yaml
- docs/MOM_parameter_doc.all
- docs/MOM_parameter_doc.debugging
- docs/MOM_parameter_doc.layout
- docs/MOM_parameter_doc.short
- field_table
- manifests/input.yaml
- The docs have been updated (they have not been updated in a while so some of the changes you see are not recent ones)
- config.yaml is pointing to an updated bathymetry file that swaps the fill value from nans to 0 (to help auto masking find the land). There is an associated update in manifests
- field table has had input units set to `none` to prevent scaling at runtime
> Fixing units, updating documentation and pointing to a new file

- MOM_input
- config.yaml
- docs/MOM_parameter_doc.all
- docs/MOM_parameter_doc.short
- docs/available_diags.000000
- manifests/input.yaml
- testing/checksum/historical-6hr-checksum.json
Ref: https://github.com/ACCESS-NRI/access-om3-configs/issues/771#issuecomment-3310434280
MOM_input, docs, docs/available_diags.000000, manifests/input.yaml
- https://github.com/ACCESS-NRI/access-om3-configs/issues/771#issuecomment-3310434280
A PR has been created for updating the documentation?
**8. …
> 100km ryf config: Add parameterisations for tidal dissipation (#562)

- MOM_input
- diagnostic_profiles/diag_table_standard
- diagnostic_profiles/source_yaml_files/diag_table_standard_source.yaml
- docs/MOM_parameter_doc.all
- docs/MOM_parameter_doc.short
- docs/available_diags.000000
- testing/checksum/historical-6hr-checksum.json
Cherry-picking the following 25km changes into `dev-MC_100km_jra_iaf`:
- Addition of diagnostics on rho2 coords from #622, #641 and #648. **These are turned off by default**
- Change to `CORIOLIS_SCHEME = 'SADOURNY75_ENSTRO'` from #765
- https://github.com/ACCESS-NRI/access-om3-configs/issues/771#issuecomment-3310434280
> 100km IAF: Density coord diags (#584) and CORIOLIS_SCHEME = 'SADOURNY75_ENSTRO' (#765)
